name: Build and Release

defaults:
  run:
    shell: bash -leo pipefail {0}

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Release Binaries
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Binaries
        run: |
          make all

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/nodebox-dashboard-linux-aarch64
            bin/nodebox-dashboard-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
