name: Build and Release

defaults:
  run:
    shell: bash -ileo pipefail {0}

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Release Binaries
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Tag Name
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Binaries
        run: |
          make all VERSION=${VERSION}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: |
            bin/nodebox-dashboard-${{ env.VERSION }}-linux-aarch64
            bin/nodebox-dashboard-${{ env.VERSION }}-linux-x86_64